In [549]:
import pickle
import numpy as np
from spladder.viz.graph import *
import h5py

In [550]:
matplotlib.__version__

'3.5.2'

In [551]:
import spladder
spladder.__version__

'2.4.2'

# Open Files

In [552]:
splice_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'
#splice_path = '/cluster/work/grlab/projects/projects2021-immuno_peptides/results/TCGA_for_neoepitopes/TCGA_Breast_1102_results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'

In [553]:
count_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.count.rechunked.hdf5'

In [554]:
with open(splice_path, 'rb') as graph_fp:
    (graph_data, graph_meta) = pickle.load(graph_fp, encoding='latin1')  # both graph data and meta data

In [837]:
# gene_id = 18652
# gene_id = 57526
# gene_id = 5583

# pattern_right < pattern_left (junction order)
gene_id = 5518  
pattern_right= 3067707
pattern_left = 3082387

# gene_id = 27716
# pattern_right = 12943629
# pattern_left = 12943833

# gene_id = 4952
# pattern_right = 228097862
# pattern_left = 228098777

# gene_id = 24300
# pattern_right = 41524492
# pattern_left = 41524842

gene_id = 29614
pattern_right = 53873969
pattern_left = 53874060





In [838]:
print(pattern_left > pattern_right)

True


In [839]:
gene = graph_data[gene_id]

In [840]:
gene.strand

'+'

In [841]:
print(gene.name)

ENSG00000179820.16


In [842]:
gene.from_sparse()

In [843]:
len(np.where(gene.splicegraph.edges)[1])

1726

In [844]:
len(gene.splicegraph.edges)

214

In [845]:
gene.splicegraph.vertices.shape

(2, 214)

In [846]:
np.where(gene.splicegraph.edges)

(array([  0,   1,   1, ..., 213, 213, 213]),
 array([  5,   4,   5, ..., 118, 199, 204]))

In [847]:
np.where(gene.splicegraph.edges)

(array([  0,   1,   1, ..., 213, 213, 213]),
 array([  5,   4,   5, ..., 118, 199, 204]))

# Extract the expression

In [848]:
# Some Tests
test = 11

print(gene.splicegraph.vertices[0][test], gene.splicegraph.vertices[1][test])

test = 88

print(gene.segmentgraph.segments[0][test], gene.segmentgraph.segments[1][test])

53866042 53866140
53873629 53873651


In [849]:
gene.strand

'+'

In [850]:
print(pattern_right, pattern_left)

53873969 53874060


In [851]:
[(i, seg[0], seg[1]) for i, seg in enumerate(zip(gene.segmentgraph.segments[0], gene.segmentgraph.segments[1]))]

[(0, 53864762, 53864871),
 (1, 53864871, 53864891),
 (2, 53865218, 53865404),
 (3, 53865404, 53865418),
 (4, 53865418, 53865509),
 (5, 53865509, 53865583),
 (6, 53865583, 53865604),
 (7, 53865604, 53865726),
 (8, 53865726, 53865728),
 (9, 53865728, 53865737),
 (10, 53865737, 53865933),
 (11, 53865933, 53866018),
 (12, 53866018, 53866042),
 (13, 53866042, 53866106),
 (14, 53866106, 53866124),
 (15, 53866124, 53866140),
 (16, 53866140, 53866152),
 (17, 53866152, 53866154),
 (18, 53866154, 53866157),
 (19, 53866157, 53866306),
 (20, 53866306, 53866324),
 (21, 53866324, 53866417),
 (22, 53867265, 53867465),
 (23, 53867576, 53867776),
 (24, 53867882, 53867910),
 (25, 53867910, 53867927),
 (26, 53867927, 53867942),
 (27, 53867942, 53867943),
 (28, 53867943, 53867948),
 (29, 53867948, 53868110),
 (30, 53868110, 53868127),
 (31, 53868127, 53868179),
 (32, 53868179, 53868379),
 (33, 53868379, 53868459),
 (34, 53868459, 53868470),
 (35, 53868470, 53868482),
 (36, 53868482, 53868518),
 (37, 53868

In [852]:
[(a,b) for a, b in zip(np.where(gene.segmentgraph.seg_edges)[0],np.where(gene.segmentgraph.seg_edges)[1])]

[(0, 5),
 (1, 5),
 (1, 13),
 (3, 5),
 (6, 53),
 (6, 55),
 (7, 11),
 (7, 55),
 (8, 11),
 (8, 13),
 (8, 14),
 (8, 15),
 (8, 18),
 (8, 53),
 (8, 55),
 (9, 11),
 (9, 13),
 (9, 14),
 (9, 15),
 (9, 18),
 (9, 53),
 (9, 55),
 (9, 57),
 (9, 85),
 (11, 14),
 (11, 55),
 (21, 23),
 (21, 52),
 (21, 53),
 (21, 54),
 (21, 55),
 (21, 57),
 (21, 58),
 (21, 85),
 (22, 55),
 (26, 53),
 (26, 55),
 (26, 85),
 (27, 36),
 (27, 37),
 (27, 39),
 (27, 47),
 (27, 52),
 (27, 53),
 (27, 54),
 (27, 55),
 (27, 57),
 (27, 58),
 (27, 84),
 (27, 85),
 (28, 36),
 (28, 39),
 (28, 53),
 (28, 55),
 (28, 57),
 (28, 58),
 (28, 84),
 (28, 85),
 (29, 39),
 (29, 53),
 (29, 55),
 (29, 57),
 (29, 58),
 (29, 85),
 (30, 39),
 (30, 55),
 (32, 53),
 (32, 55),
 (39, 53),
 (39, 55),
 (39, 57),
 (39, 85),
 (40, 55),
 (42, 55),
 (45, 53),
 (45, 55),
 (50, 53),
 (50, 55),
 (50, 57),
 (58, 60),
 (58, 67),
 (58, 79),
 (58, 80),
 (58, 83),
 (58, 84),
 (58, 85),
 (58, 86),
 (58, 87),
 (58, 91),
 (61, 85),
 (62, 84),
 (64, 85),
 (65, 85),
 (71

In [853]:
### GET THE Number of the vertexes
graph_edge_idx = None
first = np.where(gene.segmentgraph.seg_edges)[0]
second = np.where(gene.segmentgraph.seg_edges)[1]
for edge_idx in np.arange(len(first)):
    v1 = first[edge_idx]
    v2 = second[edge_idx]
    # Same - and + strand
    if (str(pattern_left) in  str(gene.segmentgraph.segments[0][v2])) and \
        (str(pattern_right) in str(gene.segmentgraph.segments[1][v1])):
        print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
        print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])

        print('vertexes in segment graph', v1, v2)
        print('edge_idx', edge_idx)
        graph_edge_idx = edge_idx
        


In [854]:
graph_edge_idx

In [855]:
# Get edge h5py indexes
if graph_edge_idx is not None:
    with h5py.File(count_path, 'r') as h5f:  
        test_edge_id = [i for i, j  in enumerate(h5f['gene_ids_edges'])  if j == gene_id]
    h5_edge = test_edge_id[graph_edge_idx]
    print('h5_edge', h5_edge, 'for', graph_edge_idx)

In [856]:
# Get expression h5py
if graph_edge_idx is not None:
    with h5py.File(count_path, 'r') as h5f: test_edg_exr=h5f['edges'][h5_edge, :]

In [857]:
# Get Strains 
if graph_edge_idx is not None:
    with h5py.File(count_path, 'r') as h5f: test_sample_id = h5f['strains'][:]

In [858]:
if graph_edge_idx is not None:
    with np.printoptions(threshold=np.inf):
        print(test_edg_exr)


In [859]:
if graph_edge_idx is not None:
    print(test_sample_id[np.where(test_edg_exr)[0]])

    print(test_edg_exr[np.where(test_edg_exr > 0)[0]])

    print(len(test_edg_exr[np.where(test_edg_exr > 0)[0]]))

# Plot splicegraph

In [806]:
from matplotlib.collections import PatchCollection
import pickle
import sys
import scipy as sp
import pdb
def plot_graph(vertices, edges, ax, xlim=None, highlight=None, highlight_color='magenta', node_color='b',
               edge_color='#999999', label=None):
    """Takes a graph given as vertices and edges and visualizes its structure"""

    start = vertices.ravel().min()
    stop = vertices.ravel().max()

    ### draw grid
    ax.grid(b=True, which='major', linestyle='--', linewidth=0.2, color='#222222')
    ax.yaxis.grid(False)

    ### nodes
    patchlist = []
    exon_num = sp.zeros((stop - start,))
    exon_loc = sp.zeros((1, stop - start))
    exon_level = sp.zeros((vertices.shape[1], )) #vertices.shape[1]))
    for i in range(vertices.shape[1]):
        cur_vertex = vertices[:, i] - start
        exon_num[cur_vertex[0]:cur_vertex[1]] += 1
        if sp.all(exon_num < 2):
            exon_loc[0, :] = exon_num
            level = 0
        elif exon_num.max() > exon_loc.shape[0]:
            exon_loc = sp.r_[exon_loc, sp.zeros((1, stop - start))]
            exon_loc[-1, cur_vertex[0]:cur_vertex[1]] = 1
            level = exon_loc.shape[0] - 1
        elif exon_num.max() <= exon_loc.shape[0]:
            idx = sp.where(sp.all(exon_loc[:, cur_vertex[0]:cur_vertex[1]] == 0, 1))[0].min()
            exon_loc[idx, cur_vertex[0]:cur_vertex[1]] = 1
            level = idx

        exon_level[i] = level

        patchlist.append(mpatches.Rectangle([cur_vertex[0] + start, 20 + (level * 20)], cur_vertex[1] - cur_vertex[0], 10, facecolor=node_color, edgecolor='none', alpha=0.7))

    ### edges
    linelist = []
    intron_loc = sp.zeros((1, stop - start))
    if edges.shape[0] > 1:
        ii, jj = sp.where(sp.triu(edges) > 0)
        for i, j in zip(ii, jj):
            if vertices[0,i] < vertices[0,j]:
                istart = vertices[1, i]
                istop = vertices[0, j]
                level1 = exon_level[i]
                level2 = exon_level[j]
            else:
                istart = vertices[1, j]
                istop = vertices[0, i]
                level1 = exon_level[j]
                level2 = exon_level[i]

            cur_intron = [istart - start, istop - start]
            intron_loc[cur_intron[0]:cur_intron[1]] += 1
            leveli = [(istart + istop) * 0.5, (level1 + level2) * 0.5]
            #ax.plot([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)
            linelist.append(mlines.Line2D([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], color=edge_color, linewidth=0.5, alpha=0.07))
            #ax.plot([leveli[0], istop], [32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)

    ### draw patches
    for node in patchlist:
        ax.add_patch(node)
    for line in linelist:
        ax.add_line(line)

    ### draw label
    if label:
        ax.text(start + (stop - start) / 2, 12, label, verticalalignment='center', horizontalalignment='center')

    ### axes
    if xlim is not None:
        ax.set_xlim(xlim)
    else:
        ax.set_xlim([max(start - 20, 0), stop + 20])
    ax.set_ylim([0, 40 + (exon_loc.shape[0] * 20)])
    ax.set_yticks([])

    ### highlight if requested
    if highlight is not None:
        rect = patches.Rectangle((highlight[0], 0), highlight[1] - highlight[0], ax.get_ylim()[1], facecolor=highlight_color, edgecolor='none', alpha=0.5)
        ax.add_patch(rect)

In [807]:
# SPlot splicegraph
# fig, ax1 = plt.subplots()
# plot_graph(gene.splicegraph.vertices, gene.splicegraph.edges, ax1)
# plt.savefig('test', bbox_inches='tight')

# Splicegraph centric approach

In [ ]:
# pattern_right = '3067707'
# pattern_left = '3082387'
# first = np.where(gene.splicegraph.edges)[0]
# second = np.where(gene.splicegraph.edges)[1]
# for idx in np.arange(len(first)):
#     i = first[idx]
#     j = second[idx]
#     if ((pattern_right in str(gene.splicegraph.vertices[0][i]) ) or (pattern_right in str(gene.splicegraph.vertices[1][j])))\
#     and ((pattern_left in str(gene.splicegraph.vertices[0][i]) ) or (pattern_left in str(gene.splicegraph.vertices[1][j]))):
#         print(gene.splicegraph.vertices[0][i],gene.splicegraph.vertices[1][j])
#         print(i, j)
#         print(idx)

In [ ]:
# for i, j in zip(gene.splicegraph.vertices[0], gene.splicegraph.vertices[1]):
#     print(i,j)
#     print(np.round(abs(i-j)/3))