In [1]:
import pickle
import numpy as np
from spladder.viz.graph import *
import h5py

Matplotlib created a temporary config/cache directory at /scratch/slurm-job.1000562/matplotlib-mzmyoqs8 because the default path (/cluster/customapps/biomed/grlab/users/prelotla/.cache/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.


In [2]:
matplotlib.__version__

'3.5.2'

In [3]:
import spladder
spladder.__version__

'2.4.2'

# Open Files

In [4]:
splice_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'
#splice_path = '/cluster/work/grlab/projects/projects2021-immuno_peptides/results/TCGA_for_neoepitopes/TCGA_Breast_1102_results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'

In [5]:
count_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.count.rechunked.hdf5'

In [6]:
with open(splice_path, 'rb') as graph_fp:
    (graph_data, graph_meta) = pickle.load(graph_fp, encoding='latin1')  # both graph data and meta data

In [340]:
gene_id = 18652
gene_id = 57526
gene_id = 5583

gene_id = 5518  
pattern_right= '3067707' 
pattern_left = '3082387'

gene_id = 27716
pattern_right = '12943629' 
pattern_left = '12943833'

# gene_id = 4952
# pattern_right = '228097862'
# pattern_left = '228098777'

# gene_id = 24300
# pattern_right = '41524492'
# pattern_left = '41524842'

In [341]:
gene = graph_data[gene_id]

In [342]:
gene.strand

'+'

In [343]:
print(gene.name)

ENSG00000179218.13


In [344]:
gene.from_sparse()

In [345]:
len(np.where(gene.splicegraph.edges)[1])

4544

In [346]:
len(gene.splicegraph.edges)

779

In [347]:
gene.splicegraph.vertices.shape

(2, 779)

In [348]:
np.where(gene.splicegraph.edges)

(array([  0,   1,   2, ..., 777, 777, 778]),
 array([131, 131, 131, ..., 391, 744, 405]))

In [349]:
np.where(gene.splicegraph.edges)

(array([  0,   1,   2, ..., 777, 777, 778]),
 array([131, 131, 131, ..., 391, 744, 405]))

# Extract the expression

In [350]:
# Some Tests
test = 11

print(gene.splicegraph.vertices[0][test], gene.splicegraph.vertices[1][test])

test = 88

print(gene.segmentgraph.segments[0][test], gene.segmentgraph.segments[1][test])

12938577 12938685
12939971 12940052


In [351]:
gene.strand

'+'

In [356]:
print(pattern_right, pattern_left)

12943629 12943833


In [ ]:
 (194, 12943628, 12943629), (195, 12943629, 12943693),
    (275, 12943832, 12943833),
 (276, 12943833, 12943835),

In [358]:
[(i, seg[0], seg[1]) for i, seg in enumerate(zip(gene.segmentgraph.segments[0], gene.segmentgraph.segments[1]))]

[(0, 12933741, 12933941),
 (1, 12933941, 12933944),
 (2, 12933944, 12934144),
 (3, 12938356, 12938556),
 (4, 12938577, 12938606),
 (5, 12938606, 12938613),
 (6, 12938613, 12938639),
 (7, 12938639, 12938642),
 (8, 12938642, 12938644),
 (9, 12938644, 12938648),
 (10, 12938648, 12938660),
 (11, 12938660, 12938667),
 (12, 12938667, 12938671),
 (13, 12938671, 12938679),
 (14, 12938679, 12938685),
 (15, 12938685, 12938688),
 (16, 12938688, 12938692),
 (17, 12938692, 12938694),
 (18, 12938694, 12938700),
 (19, 12938700, 12938711),
 (20, 12938711, 12938735),
 (21, 12938735, 12938741),
 (22, 12938741, 12938742),
 (23, 12938742, 12938744),
 (24, 12938744, 12938747),
 (25, 12938747, 12938756),
 (26, 12938756, 12938770),
 (27, 12938770, 12938844),
 (28, 12938844, 12938861),
 (29, 12938861, 12938963),
 (30, 12938963, 12939008),
 (31, 12939008, 12939016),
 (32, 12939016, 12939050),
 (33, 12939050, 12939132),
 (34, 12939132, 12939133),
 (35, 12939133, 12939134),
 (36, 12939134, 12939155),
 (37, 12939

In [359]:
[(a,b) for a, b in zip(np.where(gene.segmentgraph.seg_edges)[0],np.where(gene.segmentgraph.seg_edges)[1])]

[(0, 35),
 (2, 35),
 (3, 35),
 (6, 41),
 (7, 40),
 (8, 16),
 (9, 13),
 (10, 16),
 (11, 20),
 (13, 25),
 (14, 22),
 (14, 24),
 (15, 23),
 (15, 25),
 (16, 21),
 (17, 25),
 (18, 25),
 (25, 35),
 (25, 41),
 (26, 33),
 (26, 35),
 (26, 36),
 (26, 41),
 (26, 45),
 (26, 53),
 (26, 60),
 (26, 73),
 (26, 89),
 (27, 35),
 (27, 45),
 (27, 53),
 (27, 60),
 (27, 73),
 (27, 89),
 (28, 35),
 (28, 45),
 (28, 53),
 (29, 35),
 (29, 53),
 (30, 35),
 (30, 45),
 (30, 53),
 (30, 54),
 (30, 60),
 (30, 73),
 (31, 34),
 (36, 44),
 (37, 42),
 (37, 43),
 (38, 47),
 (45, 53),
 (45, 89),
 (45, 95),
 (47, 53),
 (48, 53),
 (49, 52),
 (49, 53),
 (49, 54),
 (49, 60),
 (49, 73),
 (49, 86),
 (49, 89),
 (49, 91),
 (49, 95),
 (49, 105),
 (50, 53),
 (54, 77),
 (55, 67),
 (55, 70),
 (56, 72),
 (57, 66),
 (58, 61),
 (61, 80),
 (62, 78),
 (63, 69),
 (64, 80),
 (67, 76),
 (73, 81),
 (74, 79),
 (81, 89),
 (82, 89),
 (83, 86),
 (83, 89),
 (83, 91),
 (83, 103),
 (83, 105),
 (86, 89),
 (87, 89),
 (89, 96),
 (91, 107),
 (92, 108),
 

In [352]:
### GET THE Number of the vertexes
first = np.where(gene.segmentgraph.seg_edges)[0]
second = np.where(gene.segmentgraph.seg_edges)[1]
for edge_idx in np.arange(len(first)):
    v1 = first[edge_idx]
    v2 = second[edge_idx]
    if gene.strand == '+':
        if (pattern_left in  str(gene.segmentgraph.segments[0][v2])) and \
            (pattern_right in str(gene.segmentgraph.segments[1][v1])):
            print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
            print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
            print('vertexes in segment graph', v1, v2)
            print('edge_idx', edge_idx)
            graph_edge_idx = edge_idx
        
    elif gene.strand == '-':
        if (pattern_left in str(gene.segmentgraph.segments[0][v2])) and  \
            (pattern_right in str(gene.segmentgraph.segments[0][v1])):
            print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
            print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
            print('vertexes in segment graph', v1, v2)
            print('edge_idx', edge_idx)
            graph_edge_idx = edge_idx

In [353]:
gene.segmentgraph.segments[1]

array([12933941, 12933944, 12934144, 12938556, 12938606, 12938613,
       12938639, 12938642, 12938644, 12938648, 12938660, 12938667,
       12938671, 12938679, 12938685, 12938688, 12938692, 12938694,
       12938700, 12938711, 12938735, 12938741, 12938742, 12938744,
       12938747, 12938756, 12938770, 12938844, 12938861, 12938963,
       12939008, 12939016, 12939050, 12939132, 12939133, 12939134,
       12939155, 12939159, 12939167, 12939174, 12939175, 12939191,
       12939193, 12939196, 12939197, 12939202, 12939203, 12939233,
       12939234, 12939235, 12939335, 12939371, 12939427, 12939435,
       12939445, 12939455, 12939456, 12939457, 12939468, 12939473,
       12939496, 12939513, 12939518, 12939519, 12939525, 12939528,
       12939532, 12939534, 12939553, 12939560, 12939571, 12939577,
       12939581, 12939583, 12939585, 12939588, 12939597, 12939600,
       12939606, 12939610, 12939615, 12939629, 12939630, 12939631,
       12939771, 12939889, 12939923, 12939971, 12940052, 12940

In [339]:
### GET THE Number of the vertexes #TEST
first = np.where(gene.segmentgraph.seg_edges)[0]
second = np.where(gene.segmentgraph.seg_edges)[1]
for edge_idx in np.arange(len(first)):
    v1 = first[edge_idx]
    v2 = second[edge_idx]
    if gene.strand == '+':
        if (pattern_right in str(gene.segmentgraph.segments[1][v1])): #(pattern_left in str(gene.segmentgraph.segments[0][v1])):# and \
            print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
            print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
            print('vertexes in segment graph', v1, v2)
            print('edge_idx', edge_idx)
            graph_edge_idx = edge_idx

12943712 12943693
12943629 12943628
vertexes in segment graph 194 196
edge_idx 186
12943715 12943712
12943629 12943628
vertexes in segment graph 194 197
edge_idx 187
12943716 12943715
12943629 12943628
vertexes in segment graph 194 198
edge_idx 188
12943717 12943716
12943629 12943628
vertexes in segment graph 194 199
edge_idx 189
12943723 12943719
12943629 12943628
vertexes in segment graph 194 201
edge_idx 190
12943734 12943733
12943629 12943628
vertexes in segment graph 194 209
edge_idx 191
12943745 12943742
12943629 12943628
vertexes in segment graph 194 217
edge_idx 192
12943757 12943756
12943629 12943628
vertexes in segment graph 194 225
edge_idx 193
12943774 12943773
12943629 12943628
vertexes in segment graph 194 237
edge_idx 194
12943793 12943791
12943629 12943628
vertexes in segment graph 194 248
edge_idx 195
12943800 12943799
12943629 12943628
vertexes in segment graph 194 253
edge_idx 196
12943802 12943800
12943629 12943628
vertexes in segment graph 194 254
edge_idx 197
1294

In [331]:
pattern_right

'12943629'

In [329]:
pattern_left

'12943833'

In [311]:
# Get edge h5py indexes
with h5py.File(count_path, 'r') as h5f:  
    test_edge_id = [i for i, j  in enumerate(h5f['gene_ids_edges'])  if j == gene_id]
h5_edge = test_edge_id[graph_edge_idx]
print('h5_edge', h5_edge, 'for', graph_edge_idx)

KeyboardInterrupt: 

In [ ]:
# Get expression h5py
with h5py.File(count_path, 'r') as h5f: test_edg_exr=h5f['edges'][h5_edge, :]

In [277]:
with h5py.File(count_path, 'r') as h5f: test_sample_id = h5f['strains'][:]

In [278]:
with np.printoptions(threshold=np.inf):
    print(test_edg_exr)


[5.100e+01 1.550e+02 5.200e+01 4.700e+01 1.500e+01 4.070e+02 1.340e+02
 1.030e+02 1.600e+01 4.900e+01 3.600e+01 2.000e+00 2.800e+01 7.200e+01
 3.800e+01 4.200e+01 1.800e+01 1.700e+01 4.800e+01 2.500e+01 3.600e+01
 8.700e+01 2.900e+01 2.600e+01 4.900e+01 1.900e+01 5.800e+01 1.600e+01
 3.000e+00 4.800e+01 8.100e+01 4.900e+01 6.700e+01 9.000e+00 4.400e+01
 1.130e+02 6.200e+01 1.600e+01 4.700e+01 6.600e+01 2.900e+01 1.840e+02
 5.700e+01 3.000e+00 1.080e+02 2.800e+01 7.700e+01 6.300e+01 1.280e+02
 6.900e+01 5.200e+01 1.100e+02 4.800e+01 2.100e+01 3.500e+01 9.600e+01
 1.900e+01 1.580e+02 3.000e+01 2.900e+01 2.300e+01 3.700e+01 3.800e+01
 4.500e+01 4.700e+01 8.400e+01 6.300e+01 9.000e+00 1.000e+01 6.000e+00
 5.400e+01 7.500e+01 4.200e+01 4.600e+01 2.000e+01 1.010e+02 4.000e+01
 5.200e+01 5.900e+01 7.800e+01 0.000e+00 1.300e+01 2.900e+01 2.100e+01
 3.300e+01 1.900e+01 5.100e+01 2.400e+01 3.300e+01 4.700e+01 1.000e+00
 1.810e+02 4.800e+01 9.500e+01 1.950e+02 9.000e+01 2.220e+02 2.700e+01
 6.000

In [279]:
print(test_sample_id[np.where(test_edg_exr)[0]])

[b'SRR1068687.all' b'SRR1068788.all' b'SRR1068808.all' ...
 b'SRR823991.all' b'SRR824015.all' b'SRR824039.all']


In [280]:
print(test_edg_exr[np.where(test_edg_exr > 0)[0]])

[ 51. 155.  52. ... 241. 162. 194.]


In [281]:
len(test_edg_exr[np.where(test_edg_exr > 0)[0]])

9541

# Plot splicegraph

In [ ]:
from matplotlib.collections import PatchCollection
import pickle
import sys
import scipy as sp
import pdb
def plot_graph(vertices, edges, ax, xlim=None, highlight=None, highlight_color='magenta', node_color='b',
               edge_color='#999999', label=None):
    """Takes a graph given as vertices and edges and visualizes its structure"""

    start = vertices.ravel().min()
    stop = vertices.ravel().max()

    ### draw grid
    ax.grid(b=True, which='major', linestyle='--', linewidth=0.2, color='#222222')
    ax.yaxis.grid(False)

    ### nodes
    patchlist = []
    exon_num = sp.zeros((stop - start,))
    exon_loc = sp.zeros((1, stop - start))
    exon_level = sp.zeros((vertices.shape[1], )) #vertices.shape[1]))
    for i in range(vertices.shape[1]):
        cur_vertex = vertices[:, i] - start
        exon_num[cur_vertex[0]:cur_vertex[1]] += 1
        if sp.all(exon_num < 2):
            exon_loc[0, :] = exon_num
            level = 0
        elif exon_num.max() > exon_loc.shape[0]:
            exon_loc = sp.r_[exon_loc, sp.zeros((1, stop - start))]
            exon_loc[-1, cur_vertex[0]:cur_vertex[1]] = 1
            level = exon_loc.shape[0] - 1
        elif exon_num.max() <= exon_loc.shape[0]:
            idx = sp.where(sp.all(exon_loc[:, cur_vertex[0]:cur_vertex[1]] == 0, 1))[0].min()
            exon_loc[idx, cur_vertex[0]:cur_vertex[1]] = 1
            level = idx

        exon_level[i] = level

        patchlist.append(mpatches.Rectangle([cur_vertex[0] + start, 20 + (level * 20)], cur_vertex[1] - cur_vertex[0], 10, facecolor=node_color, edgecolor='none', alpha=0.7))

    ### edges
    linelist = []
    intron_loc = sp.zeros((1, stop - start))
    if edges.shape[0] > 1:
        ii, jj = sp.where(sp.triu(edges) > 0)
        for i, j in zip(ii, jj):
            if vertices[0,i] < vertices[0,j]:
                istart = vertices[1, i]
                istop = vertices[0, j]
                level1 = exon_level[i]
                level2 = exon_level[j]
            else:
                istart = vertices[1, j]
                istop = vertices[0, i]
                level1 = exon_level[j]
                level2 = exon_level[i]

            cur_intron = [istart - start, istop - start]
            intron_loc[cur_intron[0]:cur_intron[1]] += 1
            leveli = [(istart + istop) * 0.5, (level1 + level2) * 0.5]
            #ax.plot([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)
            linelist.append(mlines.Line2D([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], color=edge_color, linewidth=0.5, alpha=0.07))
            #ax.plot([leveli[0], istop], [32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)

    ### draw patches
    for node in patchlist:
        ax.add_patch(node)
    for line in linelist:
        ax.add_line(line)

    ### draw label
    if label:
        ax.text(start + (stop - start) / 2, 12, label, verticalalignment='center', horizontalalignment='center')

    ### axes
    if xlim is not None:
        ax.set_xlim(xlim)
    else:
        ax.set_xlim([max(start - 20, 0), stop + 20])
    ax.set_ylim([0, 40 + (exon_loc.shape[0] * 20)])
    ax.set_yticks([])

    ### highlight if requested
    if highlight is not None:
        rect = patches.Rectangle((highlight[0], 0), highlight[1] - highlight[0], ax.get_ylim()[1], facecolor=highlight_color, edgecolor='none', alpha=0.5)
        ax.add_patch(rect)

In [ ]:
# SPlot splicegraph
# fig, ax1 = plt.subplots()
# plot_graph(gene.splicegraph.vertices, gene.splicegraph.edges, ax1)
# plt.savefig('test', bbox_inches='tight')

# Splicegraph centric approach

In [ ]:
# pattern_right = '3067707'
# pattern_left = '3082387'
# first = np.where(gene.splicegraph.edges)[0]
# second = np.where(gene.splicegraph.edges)[1]
# for idx in np.arange(len(first)):
#     i = first[idx]
#     j = second[idx]
#     if ((pattern_right in str(gene.splicegraph.vertices[0][i]) ) or (pattern_right in str(gene.splicegraph.vertices[1][j])))\
#     and ((pattern_left in str(gene.splicegraph.vertices[0][i]) ) or (pattern_left in str(gene.splicegraph.vertices[1][j]))):
#         print(gene.splicegraph.vertices[0][i],gene.splicegraph.vertices[1][j])
#         print(i, j)
#         print(idx)

In [ ]:
# for i, j in zip(gene.splicegraph.vertices[0], gene.splicegraph.vertices[1]):
#     print(i,j)
#     print(np.round(abs(i-j)/3))