In [1]:
import pickle
import numpy as np
from spladder.viz.graph import *


In [2]:
matplotlib.__version__

'2.2.2'

In [3]:
import spladder
spladder.__version__

'3.0.4'

In [86]:
splice_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'
splice_path = '/cluster/work/grlab/projects/projects2021-immuno_peptides/results/TCGA_for_neoepitopes/TCGA_Breast_1102_results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'

In [87]:
with open(splice_path, 'rb') as graph_fp:
    (graph_data, graph_meta) = pickle.load(graph_fp, encoding='latin1')  # both graph data and meta data

In [88]:
gene_id = 18652
gene_id = 57526
gene_id = 5583
#gene_id = 100

In [89]:
gene = graph_data[gene_id]

In [90]:
gene.strand

'-'

In [91]:
print(gene.name)

ENSG00000057608.17


In [92]:
gene.from_sparse()

In [93]:
len(np.where(gene.splicegraph.edges)[1])

1136

In [94]:
len(gene.splicegraph.edges)

193

In [95]:
gene.splicegraph.vertices.shape

(2, 193)

In [96]:
gene.splicegraph.vertices

array([[5764958, 5765222, 5765222, 5765222, 5765222, 5765222, 5765222,
        5765222, 5765222, 5765222, 5765222, 5765222, 5765222, 5765222,
        5765222, 5765222, 5765222, 5765222, 5765222, 5765222, 5765222,
        5765228, 5765228, 5765228, 5765228, 5765228, 5765228, 5765228,
        5765228, 5765228, 5765228, 5765228, 5765228, 5765228, 5765228,
        5765228, 5765228, 5765848, 5765848, 5765848, 5765848, 5765848,
        5765875, 5765880, 5765913, 5765916, 5765946, 5765952, 5765953,
        5765953, 5765982, 5765986, 5766000, 5766019, 5766051, 5766081,
        5766091, 5766105, 5766116, 5766132, 5766240, 5766240, 5766240,
        5766240, 5766240, 5766240, 5766240, 5766240, 5766493, 5766493,
        5766501, 5766625, 5767765, 5767854, 5767916, 5767939, 5767939,
        5768030, 5768212, 5768212, 5768212, 5768212, 5768212, 5768333,
        5768333, 5768345, 5770451, 5771868, 5772341, 5773841, 5773841,
        5774151, 5781070, 5781201, 5781201, 5781201, 5781201, 5781219,
      

In [97]:
np.where(gene.splicegraph.edges)

(array([  0,   0,   1, ..., 190, 191, 192]),
 array([ 81,  82,  50, ..., 192, 144, 190]))

In [98]:
pattern = '57657'
for i, j in zip(np.where(gene.splicegraph.edges)[0], np.where(gene.splicegraph.edges)[1]):
    if (pattern in str(gene.splicegraph.vertices[0][i]) ) or (pattern in str(gene.splicegraph.vertices[1][j])):
        print(gene.splicegraph.vertices[0][i],gene.splicegraph.vertices[1][j])

5765880 5765764
5765880 5765764
5765916 5765759
5765916 5765759
5765986 5765764
5765986 5765764
5766000 5765764
5766000 5765764
5766240 5765717
5766240 5765764
5766240 5765717
5781219 5765717
5785141 5765764


In [99]:
str(5765222) == pattern

False

In [100]:
for i, j in zip(gene.splicegraph.vertices[0], gene.splicegraph.vertices[1]):
    print(i,j)
    print(np.round(abs(i-j)/3))

5764958 5765158
67.0
5765222 5765264
14.0
5765222 5765284
21.0
5765222 5765287
22.0
5765222 5765288
22.0
5765222 5765302
27.0
5765222 5765378
52.0
5765222 5765427
68.0
5765222 5765488
89.0
5765222 5765553
110.0
5765222 5765717
165.0
5765222 5765759
179.0
5765222 5765764
181.0
5765222 5765885
221.0
5765222 5765926
235.0
5765222 5765933
237.0
5765222 5766079
286.0
5765222 5766145
308.0
5765222 5766152
310.0
5765222 5766159
312.0
5765222 5766174
317.0
5765228 5765264
12.0
5765228 5765284
19.0
5765228 5765287
20.0
5765228 5765288
20.0
5765228 5765302
25.0
5765228 5765378
50.0
5765228 5765427
66.0
5765228 5765488
87.0
5765228 5765553
108.0
5765228 5765759
177.0
5765228 5765764
179.0
5765228 5765885
219.0
5765228 5765926
233.0
5765228 5765933
235.0
5765228 5766079
284.0
5765228 5766152
308.0
5765848 5765885
12.0
5765848 5765926
26.0
5765848 5765933
28.0
5765848 5766079
77.0
5765848 5766152
101.0
5765875 5766152
92.0
5765880 5766152
91.0
5765913 5766152
80.0
5765916 5766152
79.0
5765946 57661

In [68]:
plot_graph

<function __main__.plot_graph(vertices, edges, ax, xlim=None, highlight=None, highlight_color='magenta', node_color='b', edge_color='#999999', label=None)>

In [69]:
from matplotlib.collections import PatchCollection
import pickle
import sys
import scipy as sp
import pdb
def plot_graph(vertices, edges, ax, xlim=None, highlight=None, highlight_color='magenta', node_color='b',
               edge_color='#999999', label=None):
    """Takes a graph given as vertices and edges and visualizes its structure"""

    start = vertices.ravel().min()
    stop = vertices.ravel().max()

    ### draw grid
    ax.grid(b=True, which='major', linestyle='--', linewidth=0.2, color='#222222')
    ax.yaxis.grid(False)

    ### nodes
    patchlist = []
    exon_num = sp.zeros((stop - start,))
    exon_loc = sp.zeros((1, stop - start))
    exon_level = sp.zeros((vertices.shape[1], )) #vertices.shape[1]))
    for i in range(vertices.shape[1]):
        cur_vertex = vertices[:, i] - start
        exon_num[cur_vertex[0]:cur_vertex[1]] += 1
        if sp.all(exon_num < 2):
            exon_loc[0, :] = exon_num
            level = 0
        elif exon_num.max() > exon_loc.shape[0]:
            exon_loc = sp.r_[exon_loc, sp.zeros((1, stop - start))]
            exon_loc[-1, cur_vertex[0]:cur_vertex[1]] = 1
            level = exon_loc.shape[0] - 1
        elif exon_num.max() <= exon_loc.shape[0]:
            idx = sp.where(sp.all(exon_loc[:, cur_vertex[0]:cur_vertex[1]] == 0, 1))[0].min()
            exon_loc[idx, cur_vertex[0]:cur_vertex[1]] = 1
            level = idx

        exon_level[i] = level

        patchlist.append(mpatches.Rectangle([cur_vertex[0] + start, 20 + (level * 20)], cur_vertex[1] - cur_vertex[0], 10, facecolor=node_color, edgecolor='none', alpha=0.7))

    ### edges
    linelist = []
    intron_loc = sp.zeros((1, stop - start))
    if edges.shape[0] > 1:
        ii, jj = sp.where(sp.triu(edges) > 0)
        for i, j in zip(ii, jj):
            if vertices[0,i] < vertices[0,j]:
                istart = vertices[1, i]
                istop = vertices[0, j]
                level1 = exon_level[i]
                level2 = exon_level[j]
            else:
                istart = vertices[1, j]
                istop = vertices[0, i]
                level1 = exon_level[j]
                level2 = exon_level[i]

            cur_intron = [istart - start, istop - start]
            intron_loc[cur_intron[0]:cur_intron[1]] += 1
            leveli = [(istart + istop) * 0.5, (level1 + level2) * 0.5]
            #ax.plot([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)
            linelist.append(mlines.Line2D([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], color=edge_color, linewidth=0.5, alpha=0.07))
            #ax.plot([leveli[0], istop], [32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)

    ### draw patches
    for node in patchlist:
        ax.add_patch(node)
    for line in linelist:
        ax.add_line(line)

    ### draw label
    if label:
        ax.text(start + (stop - start) / 2, 12, label, verticalalignment='center', horizontalalignment='center')

    ### axes
    if xlim is not None:
        ax.set_xlim(xlim)
    else:
        ax.set_xlim([max(start - 20, 0), stop + 20])
    ax.set_ylim([0, 40 + (exon_loc.shape[0] * 20)])
    ax.set_yticks([])

    ### highlight if requested
    if highlight is not None:
        rect = patches.Rectangle((highlight[0], 0), highlight[1] - highlight[0], ax.get_ylim()[1], facecolor=highlight_color, edgecolor='none', alpha=0.5)
        ax.add_patch(rect)

In [70]:
fig, ax1 = plt.subplots()
plot_graph(gene.splicegraph.vertices, gene.splicegraph.edges, ax1)
plt.savefig('test', bbox_inches='tight')

/cluster/customapps/biomed/grlab/users/prelotla/software/miniconda/envs/matplot/lib/python3.7/site-packages/ipykernel_launcher.py:19: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
/cluster/customapps/biomed/grlab/users/prelotla/software/miniconda/envs/matplot/lib/python3.7/site-packages/ipykernel_launcher.py:20: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
/cluster/customapps/biomed/grlab/users/prelotla/software/miniconda/envs/matplot/lib/python3.7/site-packages/ipykernel_launcher.py:21: DeprecationWarning: scipy.zeros is deprecated and will be removed in SciPy 2.0.0, use numpy.zeros instead
/cluster/customapps/biomed/grlab/users/prelotla/software/miniconda/envs/matplot/lib/python3.7/site-packages/ipykernel_launcher.py:25: DeprecationWarning: scipy.all is deprecated and will be removed in SciPy 2.0.0, use numpy.all instead
/cluster/customapps/biomed/grlab/users/prelo