In [549]:
import pickle
import numpy as np
from spladder.viz.graph import *
import h5py

In [550]:
matplotlib.__version__

'3.5.2'

In [551]:
import spladder
spladder.__version__

'2.4.2'

# Open Files

In [552]:
splice_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'
#splice_path = '/cluster/work/grlab/projects/projects2021-immuno_peptides/results/TCGA_for_neoepitopes/TCGA_Breast_1102_results/splicing/spladder/genes_graph_conf2.merge_graphs.pickle'

In [553]:
count_path = '/cluster/work/grlab/projects/GTEx/rna_gencode32_realign/results/splicing/spladder/genes_graph_conf2.merge_graphs.count.rechunked.hdf5'

In [554]:
with open(splice_path, 'rb') as graph_fp:
    (graph_data, graph_meta) = pickle.load(graph_fp, encoding='latin1')  # both graph data and meta data

In [555]:
# gene_id = 18652
# gene_id = 57526
# gene_id = 5583

# gene_id = 5518  
# pattern_right= '3067707' 
# pattern_left = '3082387'

gene_id = 27716
pattern_right = '12943629' 
pattern_left = '12943833'

# gene_id = 4952
# pattern_right = '228097862'
# pattern_left = '228098777'

# gene_id = 24300
# pattern_right = '41524492'
# pattern_left = '41524842'

In [556]:
gene = graph_data[gene_id]

In [557]:
gene.strand

'+'

In [558]:
print(gene.name)

ENSG00000179218.13


In [559]:
gene.from_sparse()

In [560]:
len(np.where(gene.splicegraph.edges)[1])

4544

In [561]:
len(gene.splicegraph.edges)

779

In [562]:
gene.splicegraph.vertices.shape

(2, 779)

In [563]:
np.where(gene.splicegraph.edges)

(array([  0,   1,   2, ..., 777, 777, 778]),
 array([131, 131, 131, ..., 391, 744, 405]))

In [564]:
np.where(gene.splicegraph.edges)

(array([  0,   1,   2, ..., 777, 777, 778]),
 array([131, 131, 131, ..., 391, 744, 405]))

# Extract the expression

In [565]:
# Some Tests
test = 11

print(gene.splicegraph.vertices[0][test], gene.splicegraph.vertices[1][test])

test = 88

print(gene.segmentgraph.segments[0][test], gene.segmentgraph.segments[1][test])

12938577 12938685
12939971 12940052


In [566]:
gene.strand

'+'

In [567]:
print(pattern_right, pattern_left)

12943629 12943833


In [568]:
[(i, seg[0], seg[1]) for i, seg in enumerate(zip(gene.segmentgraph.segments[0], gene.segmentgraph.segments[1]))]

[(0, 12933741, 12933941),
 (1, 12933941, 12933944),
 (2, 12933944, 12934144),
 (3, 12938356, 12938556),
 (4, 12938577, 12938606),
 (5, 12938606, 12938613),
 (6, 12938613, 12938639),
 (7, 12938639, 12938642),
 (8, 12938642, 12938644),
 (9, 12938644, 12938648),
 (10, 12938648, 12938660),
 (11, 12938660, 12938667),
 (12, 12938667, 12938671),
 (13, 12938671, 12938679),
 (14, 12938679, 12938685),
 (15, 12938685, 12938688),
 (16, 12938688, 12938692),
 (17, 12938692, 12938694),
 (18, 12938694, 12938700),
 (19, 12938700, 12938711),
 (20, 12938711, 12938735),
 (21, 12938735, 12938741),
 (22, 12938741, 12938742),
 (23, 12938742, 12938744),
 (24, 12938744, 12938747),
 (25, 12938747, 12938756),
 (26, 12938756, 12938770),
 (27, 12938770, 12938844),
 (28, 12938844, 12938861),
 (29, 12938861, 12938963),
 (30, 12938963, 12939008),
 (31, 12939008, 12939016),
 (32, 12939016, 12939050),
 (33, 12939050, 12939132),
 (34, 12939132, 12939133),
 (35, 12939133, 12939134),
 (36, 12939134, 12939155),
 (37, 12939

In [569]:
[(a,b) for a, b in zip(np.where(gene.segmentgraph.seg_edges)[0],np.where(gene.segmentgraph.seg_edges)[1])]

[(0, 35),
 (2, 35),
 (3, 35),
 (6, 41),
 (7, 40),
 (8, 16),
 (9, 13),
 (10, 16),
 (11, 20),
 (13, 25),
 (14, 22),
 (14, 24),
 (15, 23),
 (15, 25),
 (16, 21),
 (17, 25),
 (18, 25),
 (25, 35),
 (25, 41),
 (26, 33),
 (26, 35),
 (26, 36),
 (26, 41),
 (26, 45),
 (26, 53),
 (26, 60),
 (26, 73),
 (26, 89),
 (27, 35),
 (27, 45),
 (27, 53),
 (27, 60),
 (27, 73),
 (27, 89),
 (28, 35),
 (28, 45),
 (28, 53),
 (29, 35),
 (29, 53),
 (30, 35),
 (30, 45),
 (30, 53),
 (30, 54),
 (30, 60),
 (30, 73),
 (31, 34),
 (36, 44),
 (37, 42),
 (37, 43),
 (38, 47),
 (45, 53),
 (45, 89),
 (45, 95),
 (47, 53),
 (48, 53),
 (49, 52),
 (49, 53),
 (49, 54),
 (49, 60),
 (49, 73),
 (49, 86),
 (49, 89),
 (49, 91),
 (49, 95),
 (49, 105),
 (50, 53),
 (54, 77),
 (55, 67),
 (55, 70),
 (56, 72),
 (57, 66),
 (58, 61),
 (61, 80),
 (62, 78),
 (63, 69),
 (64, 80),
 (67, 76),
 (73, 81),
 (74, 79),
 (81, 89),
 (82, 89),
 (83, 86),
 (83, 89),
 (83, 91),
 (83, 103),
 (83, 105),
 (86, 89),
 (87, 89),
 (89, 96),
 (91, 107),
 (92, 108),
 

In [577]:
### GET THE Number of the vertexes
graph_edge_idx = None
first = np.where(gene.segmentgraph.seg_edges)[0]
second = np.where(gene.segmentgraph.seg_edges)[1]
for edge_idx in np.arange(len(first)):
    v1 = first[edge_idx]
    v2 = second[edge_idx]
    if gene.strand == '+':
        if (pattern_left in  str(gene.segmentgraph.segments[0][v2])) and \
            (pattern_right in str(gene.segmentgraph.segments[1][v1])):
            print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
            print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
            print('vertexes in segment graph', v1, v2)
            print('edge_idx', edge_idx)
            graph_edge_idx = edge_idx
        
    elif gene.strand == '-':
        if (pattern_left in str(gene.segmentgraph.segments[0][v2])) and  \
            (pattern_right in str(gene.segmentgraph.segments[0][v1])):
            print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
            print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
            print('vertexes in segment graph', v1, v2)
            print('edge_idx', edge_idx)
            graph_edge_idx = edge_idx

In [578]:
# ### GET THE Number of the vertexes
# first = np.where(gene.segmentgraph.seg_edges)[0]
# second = np.where(gene.segmentgraph.seg_edges)[1]
# for edge_idx in np.arange(len(first)):
#     v1 = first[edge_idx]
#     v2 = second[edge_idx]
#     if gene.strand == '+':
#         if (pattern_left in  str(gene.segmentgraph.segments[0][v2])) and \
#             (pattern_right in str(gene.segmentgraph.segments[1][v1])):
#             print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
#             print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
#             print('vertexes in segment graph', v1, v2)
#             print('edge_idx', edge_idx)
#             graph_edge_idx = edge_idx
        
#     elif gene.strand == '-':
#         if (pattern_left in str(gene.segmentgraph.segments[0][v2])) and  \
#             (pattern_right in str(gene.segmentgraph.segments[0][v1])):
#             print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
#             print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
#             print('vertexes in segment graph', v1, v2)
#             print('edge_idx', edge_idx)
#             graph_edge_idx = edge_idx

In [579]:
# ### GET THE Number of the vertexes #TEST
# first = np.where(gene.segmentgraph.seg_edges)[0]
# second = np.where(gene.segmentgraph.seg_edges)[1]
# for edge_idx in np.arange(len(first)):
#     v1 = first[edge_idx]
#     v2 = second[edge_idx]
#     if gene.strand == '+':
#         if (pattern_right in str(gene.segmentgraph.segments[1][v1])): #(pattern_left in str(gene.segmentgraph.segments[0][v1])):# and \
#             print(gene.segmentgraph.segments[1][v2] , gene.segmentgraph.segments[0][v2])
#             print(gene.segmentgraph.segments[1][v1] , gene.segmentgraph.segments[0][v1])
#             print('vertexes in segment graph', v1, v2)
#             print('edge_idx', edge_idx)
#             graph_edge_idx = edge_idx

In [580]:
pattern_right

'12943629'

In [581]:
pattern_left

'12943833'

In [587]:
graph_edge_idx

In [582]:
# Get edge h5py indexes
if graph_edge_idx is not None:
    with h5py.File(count_path, 'r') as h5f:  
        test_edge_id = [i for i, j  in enumerate(h5f['gene_ids_edges'])  if j == gene_id]
    h5_edge = test_edge_id[graph_edge_idx]
    print('h5_edge', h5_edge, 'for', graph_edge_idx)

In [583]:
# Get expression h5py
if graph_edge_idx is not None:
    with h5py.File(count_path, 'r') as h5f: test_edg_exr=h5f['edges'][h5_edge, :]

In [584]:
# Get Strains 
if graph_edge_idx is not None:
    with h5py.File(count_path, 'r') as h5f: test_sample_id = h5f['strains'][:]

In [585]:
if graph_edge_idx is not None:
    with np.printoptions(threshold=np.inf):
        print(test_edg_exr)


In [586]:
if graph_edge_idx is not None:
    print(test_sample_id[np.where(test_edg_exr)[0]])

    print(test_edg_exr[np.where(test_edg_exr > 0)[0]])

    len(test_edg_exr[np.where(test_edg_exr > 0)[0]])

# Plot splicegraph

In [ ]:
from matplotlib.collections import PatchCollection
import pickle
import sys
import scipy as sp
import pdb
def plot_graph(vertices, edges, ax, xlim=None, highlight=None, highlight_color='magenta', node_color='b',
               edge_color='#999999', label=None):
    """Takes a graph given as vertices and edges and visualizes its structure"""

    start = vertices.ravel().min()
    stop = vertices.ravel().max()

    ### draw grid
    ax.grid(b=True, which='major', linestyle='--', linewidth=0.2, color='#222222')
    ax.yaxis.grid(False)

    ### nodes
    patchlist = []
    exon_num = sp.zeros((stop - start,))
    exon_loc = sp.zeros((1, stop - start))
    exon_level = sp.zeros((vertices.shape[1], )) #vertices.shape[1]))
    for i in range(vertices.shape[1]):
        cur_vertex = vertices[:, i] - start
        exon_num[cur_vertex[0]:cur_vertex[1]] += 1
        if sp.all(exon_num < 2):
            exon_loc[0, :] = exon_num
            level = 0
        elif exon_num.max() > exon_loc.shape[0]:
            exon_loc = sp.r_[exon_loc, sp.zeros((1, stop - start))]
            exon_loc[-1, cur_vertex[0]:cur_vertex[1]] = 1
            level = exon_loc.shape[0] - 1
        elif exon_num.max() <= exon_loc.shape[0]:
            idx = sp.where(sp.all(exon_loc[:, cur_vertex[0]:cur_vertex[1]] == 0, 1))[0].min()
            exon_loc[idx, cur_vertex[0]:cur_vertex[1]] = 1
            level = idx

        exon_level[i] = level

        patchlist.append(mpatches.Rectangle([cur_vertex[0] + start, 20 + (level * 20)], cur_vertex[1] - cur_vertex[0], 10, facecolor=node_color, edgecolor='none', alpha=0.7))

    ### edges
    linelist = []
    intron_loc = sp.zeros((1, stop - start))
    if edges.shape[0] > 1:
        ii, jj = sp.where(sp.triu(edges) > 0)
        for i, j in zip(ii, jj):
            if vertices[0,i] < vertices[0,j]:
                istart = vertices[1, i]
                istop = vertices[0, j]
                level1 = exon_level[i]
                level2 = exon_level[j]
            else:
                istart = vertices[1, j]
                istop = vertices[0, i]
                level1 = exon_level[j]
                level2 = exon_level[i]

            cur_intron = [istart - start, istop - start]
            intron_loc[cur_intron[0]:cur_intron[1]] += 1
            leveli = [(istart + istop) * 0.5, (level1 + level2) * 0.5]
            #ax.plot([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)
            linelist.append(mlines.Line2D([istart, leveli[0], istop], [25 + (level1 * 20), 32 + (leveli[1] * 20), 25 + (level2 * 20)], color=edge_color, linewidth=0.5, alpha=0.07))
            #ax.plot([leveli[0], istop], [32 + (leveli[1] * 20), 25 + (level2 * 20)], '-', color=edge_color, linewidth=0.5)

    ### draw patches
    for node in patchlist:
        ax.add_patch(node)
    for line in linelist:
        ax.add_line(line)

    ### draw label
    if label:
        ax.text(start + (stop - start) / 2, 12, label, verticalalignment='center', horizontalalignment='center')

    ### axes
    if xlim is not None:
        ax.set_xlim(xlim)
    else:
        ax.set_xlim([max(start - 20, 0), stop + 20])
    ax.set_ylim([0, 40 + (exon_loc.shape[0] * 20)])
    ax.set_yticks([])

    ### highlight if requested
    if highlight is not None:
        rect = patches.Rectangle((highlight[0], 0), highlight[1] - highlight[0], ax.get_ylim()[1], facecolor=highlight_color, edgecolor='none', alpha=0.5)
        ax.add_patch(rect)

In [ ]:
# SPlot splicegraph
# fig, ax1 = plt.subplots()
# plot_graph(gene.splicegraph.vertices, gene.splicegraph.edges, ax1)
# plt.savefig('test', bbox_inches='tight')

# Splicegraph centric approach

In [ ]:
# pattern_right = '3067707'
# pattern_left = '3082387'
# first = np.where(gene.splicegraph.edges)[0]
# second = np.where(gene.splicegraph.edges)[1]
# for idx in np.arange(len(first)):
#     i = first[idx]
#     j = second[idx]
#     if ((pattern_right in str(gene.splicegraph.vertices[0][i]) ) or (pattern_right in str(gene.splicegraph.vertices[1][j])))\
#     and ((pattern_left in str(gene.splicegraph.vertices[0][i]) ) or (pattern_left in str(gene.splicegraph.vertices[1][j]))):
#         print(gene.splicegraph.vertices[0][i],gene.splicegraph.vertices[1][j])
#         print(i, j)
#         print(idx)

In [ ]:
# for i, j in zip(gene.splicegraph.vertices[0], gene.splicegraph.vertices[1]):
#     print(i,j)
#     print(np.round(abs(i-j)/3))